name: Generate artifacts to publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          chmod +x ./scripts/generateChromeExtension.sh
          ./scripts/generateChromeExtension.sh
      - uses: actions/upload-artifact@v3
        with:
          name: jwt-dev-inspector-chrome
          path: jwt-dev-inspector-chrome.zip

  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          chmod +x ./scripts/generateFirefoxExtension.sh
          ./scripts/generateFirefoxExtension.sh
      - uses: actions/upload-artifact@v3
        with:
          name: jwt-dev-inspector-firefox
          path: jwt-dev-inspector-firefox.xpi

  edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          chmod +x ./scripts/generateEdgeExtension.sh
          ./scripts/generateEdgeExtension.sh
      - uses: actions/upload-artifact@v3
        with:
          name: jwt-dev-inspector-edge
          path: jwt-dev-inspector-edge.zip